version: 2
jobs:
  build:
    working-directory: ~/circleci-enkan
    docker:
      - image: circleci/openjdk:9-jdk-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: circleci-enkan-{{ checksum "pom.xml" }}
      - run: cd enkan-parent
      - run: mvn -e package dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-enkan-{{ checksum "pom.xml" }}
      - run: mvn -e test
      - store_test_results:
          path: target/surefire-reports
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
