jackson.IO_ERROR.problem=An I/O error occurred during bean conversion.
jackson.IO_ERROR.solution=Check that the source and destination objects are serializable/deserializable by Jackson.
jackson.UNSUPPORTED_COPY_OPTION.problem=CopyOption {0} is not supported.
jackson.UNSUPPORTED_COPY_OPTION.solution={1}
