jpa.NOT_ENTITY_MANAGEABLE_REQUEST.problem=The request is not entityManageable
jpa.NOT_ENTITY_MANAGEABLE_REQUEST.solution=Use EntityManagerMiddleware
jpa.UNSUPPORTED_TX_TYPE.problem=Transaction type {0} is not supported by NonJtaTransactionMiddleware.
jpa.UNSUPPORTED_TX_TYPE.solution=Use REQUIRED or REQUIRES_NEW for @Transactional on your controller.