package kotowari.middleware;

import enkan.Middleware;
import enkan.MiddlewareChain;
import enkan.data.HttpRequest;
import enkan.data.Routable;
import enkan.exception.MisconfigurationException;
import enkan.system.inject.ComponentInjector;
import kotowari.inject.ParameterInjector;
import kotowari.inject.parameter.*;
import kotowari.util.ParameterUtils;

import jakarta.annotation.PostConstruct;
import java.lang.invoke.CallSite;
import java.lang.invoke.LambdaMetafactory;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.Method;
import java.lang.reflect.Parameter;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

import static enkan.util.ReflectionUtils.*;

/**
 * Kotowari endpoint.
 * This middleware inject arguments to controller method.
 *
 * <ul>
 *     <li>HttpRequest - Inject a request object.</li>
 *     <li>Map - Inject parsed request parameters.</li>
 *     <li>JavaBean - Inject form.</li>
 * </ul>
 *
 * @author kawasima
 */
@enkan.annotation.Middleware(name = "controllerInvoker", dependencies = "params")
public class ControllerInvokerMiddleware<RES> implements Middleware<HttpRequest, RES, Void, Void> {
    private final Map<Class<?>, Object> controllerCache = new ConcurrentHashMap<>();
    private final Map<Method, MethodInvocation> methodCache = new ConcurrentHashMap<>();
    private final ComponentInjector componentInjector;
    private static final ParameterInjector<?> BODY_SERIALIZABLE_INJECTOR = new BodySerializableInjector<>();
    private List<ParameterInjector<?>> parameterInjectors;

    /**
     * A fast invoker generated by {@link LambdaMetafactory} that dispatches
     * controller method calls without the overhead of {@link Method#invoke}.
     */
    @FunctionalInterface
    private interface ControllerInvoker {
        Object invoke(Object controller, Object[] args) throws Throwable;
    }

    /**
     * Cached per-method invocation data: resolved injectors and the
     * LambdaMetafactory-generated invoker.
     */
    private record MethodInvocation(ParameterInjector<?>[] injectors, ControllerInvoker invoker) {}

    public ControllerInvokerMiddleware(ComponentInjector componentInjector) {
        this.componentInjector = componentInjector;
    }

    @PostConstruct
    protected void setupParameterInjectors() {
        if (parameterInjectors == null) {
            parameterInjectors = ParameterUtils.getDefaultParameterInjectors();
        }
    }

    /**
     * Resolve injectors for each parameter of the given method by type only.
     *
     * <p>All built-in {@link ParameterInjector#isApplicable} implementations
     * determine applicability solely from the parameter type, so passing
     * {@code null} for the request is safe.  Custom injectors that rely on
     * request state at applicability-check time are not supported by this
     * caching strategy and must be handled separately.
     */
    private ParameterInjector<?>[] resolveInjectors(Method method) {
        Parameter[] parameters = method.getParameters();
        ParameterInjector<?>[] injectors = new ParameterInjector<?>[parameters.length];
        for (int i = 0; i < parameters.length; i++) {
            Class<?> type = parameters[i].getType();
            injectors[i] = parameterInjectors.stream()
                    .filter(injector -> injector.isApplicable(type, null))
                    .findFirst()
                    .orElse(BODY_SERIALIZABLE_INJECTOR);
        }
        return injectors;
    }

    /**
     * Build a {@link ControllerInvoker} for the given method using
     * {@link LambdaMetafactory}.
     *
     * <p>The generated invoker avoids the per-call overhead of
     * {@link Method#invoke} (access checks, argument boxing into
     * {@code InvocationTargetException}) by producing a synthetic class
     * at bootstrap time that the JIT can inline.
     *
     * @param method the controller method to build an invoker for
     * @return a fast invoker, or a MethodHandle-based fallback if
     *         LambdaMetafactory cannot handle the method
     */
    private ControllerInvoker buildInvoker(Method method) {
        try {
            MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(
                    method.getDeclaringClass(), MethodHandles.lookup());
            MethodHandle handle = lookup.unreflect(method);

            int paramCount = method.getParameterCount();
            // Normalize: (DeclClass, P0, P1, ...) -> Object  →  (Object, Object, ...) -> Object
            handle = handle.asType(MethodType.genericMethodType(1 + paramCount));
            // Spread: (Object, Object[]) -> Object
            handle = handle.asSpreader(Object[].class, paramCount);

            // LambdaMetafactory: generate ControllerInvoker implementation
            MethodType invokerMethodType = MethodType.methodType(
                    Object.class, Object.class, Object[].class);
            CallSite callSite = LambdaMetafactory.metafactory(
                    lookup,
                    "invoke",
                    MethodType.methodType(ControllerInvoker.class),
                    invokerMethodType,               // erased signature
                    handle,
                    invokerMethodType                 // actual signature
            );
            return (ControllerInvoker) callSite.getTarget().invokeExact();
        } catch (Throwable e) {
            // Fallback: use MethodHandle directly (still faster than Method.invoke)
            return buildMethodHandleFallback(method);
        }
    }

    /**
     * Fallback invoker using {@link MethodHandle#invokeExact} with spreader.
     */
    private ControllerInvoker buildMethodHandleFallback(Method method) {
        try {
            MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(
                    method.getDeclaringClass(), MethodHandles.lookup());
            MethodHandle handle = lookup.unreflect(method);
            int paramCount = method.getParameterCount();
            MethodHandle spread = handle
                    .asType(MethodType.genericMethodType(1 + paramCount))
                    .asSpreader(Object[].class, paramCount);
            return spread::invoke;
        } catch (IllegalAccessException e) {
            throw new MisconfigurationException("core.ILLEGAL_ACCESS", e.getMessage(), e);
        }
    }

    private MethodInvocation resolveMethod(Method method) {
        return new MethodInvocation(resolveInjectors(method), buildInvoker(method));
    }

    /**
     * Create arguments for controller method.
     *
     * @param request the request object
     * @return arguments for controller method
     */
    protected Object[] createArguments(HttpRequest request, ParameterInjector<?>[] injectors) {
        Object[] arguments = new Object[injectors.length];
        for (int i = 0; i < injectors.length; i++) {
            arguments[i] = injectors[i].getInjectObject(request);
        }
        return arguments;
    }

    @SuppressWarnings("unchecked")
    @Override
    public <NNREQ, NNRES> RES handle(HttpRequest request, MiddlewareChain<Void, Void, NNREQ, NNRES> next) {
        if (request instanceof Routable routable) {
            Method controllerMethod = routable.getControllerMethod();
            Class<?> controllerClass = controllerMethod.getDeclaringClass();

            Object controller = controllerCache.computeIfAbsent(controllerClass, c ->
                    componentInjector != null ? componentInjector.newInstance(c)
                            : tryReflection(() -> c.getConstructor().newInstance()));

            MethodInvocation invocation = methodCache.computeIfAbsent(
                    controllerMethod, this::resolveMethod);
            Object[] arguments = createArguments(request, invocation.injectors());

            try {
                return (RES) invocation.invoker().invoke(controller, arguments);
            } catch (Error | RuntimeException e) {
                throw e;
            } catch (Throwable t) {
                throw new RuntimeException(t);
            }
        } else {
            throw new MisconfigurationException("kotowari.MISSING_IMPLEMENTATION", Routable.class);
        }
    }

    public void setParameterInjectors(List<ParameterInjector<?>> parameterInjectors) {
        this.parameterInjectors = parameterInjectors;
    }
}
