doma2.UNSUPPORTED_TX_TYPE.problem={0} is not supported.
doma2.UNSUPPORTED_TX_TYPE.solution=Doma2 component supports REQUIRED and REQUIRES_NEW only.
doma2.DAO_IMPL_NOT_FOUND.problem={0} is not found.
doma2.DAO_IMPL_NOT_FOUND.solution=Confirm whether the {0} class is annotated with @Dao
doma2.TX_MANAGER_NOT_AVAILABLE.problem=TransactionManager is not available.
doma2.TX_MANAGER_NOT_AVAILABLE.solution=Set useLocalTransaction=true in DomaProvider, or ensure the DataSource is an EnkanLocalTransactionDataSource.
